/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_com_jnihello_JNIMethod */

#ifndef _Included_me_com_jnihello_JNIMethod
#define _Included_me_com_jnihello_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_com_jnihello_JNIMethod
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_com_jnihello_JNIMethod_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
